// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crudService.proto

package com.projetosd.grpc;

public final class CrudProto {
  private CrudProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crud_Dto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crud_Dto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crud_DtoList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crud_DtoList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crud_ProcessingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crud_ProcessingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crud_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crud_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021crudService.proto\022\004crud\"&\n\003Dto\022\t\n\001i\030\001 " +
      "\001(\005\022\t\n\001s\030\002 \001(\t\022\t\n\001b\030\003 \001(\010\"!\n\007DtoList\022\026\n\003" +
      "dto\030\001 \003(\0132\t.crud.Dto\"%\n\022ProcessingRespon" +
      "se\022\017\n\007message\030\001 \001(\t\"\007\n\005Empty2\325\001\n\013CrudSer" +
      "vice\0222\n\tCreateDto\022\t.crud.Dto\032\030.crud.Proc" +
      "essingResponse\"\000\0222\n\tUpdateDto\022\t.crud.Dto" +
      "\032\030.crud.ProcessingResponse\"\000\0222\n\tDeleteDt" +
      "o\022\t.crud.Dto\032\030.crud.ProcessingResponse\"\000" +
      "\022*\n\nGetDtoList\022\013.crud.Empty\032\r.crud.DtoLi" +
      "st\"\000B(\n\022com.projetosd.grpcB\tCrudProtoP\001\242" +
      "\002\004CRUDb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_crud_Dto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_crud_Dto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crud_Dto_descriptor,
        new java.lang.String[] { "I", "S", "B", });
    internal_static_crud_DtoList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_crud_DtoList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crud_DtoList_descriptor,
        new java.lang.String[] { "Dto", });
    internal_static_crud_ProcessingResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_crud_ProcessingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crud_ProcessingResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_crud_Empty_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_crud_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crud_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
