// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crudService.proto

package com.projetosd.grpc;

public final class CrudServiceOuterClass {
  private CrudServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crud_ResponseModel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crud_ResponseModel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crud_SetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crud_SetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crud_GetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crud_GetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crud_TestAndSetRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crud_TestAndSetRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_crud_DelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_crud_DelRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021crudService.proto\022\004crud\"2\n\rResponseMod" +
      "el\022\017\n\007success\030\001 \001(\010\022\020\n\010response\030\002 \001(\t\")\n" +
      "\nSetRequest\022\n\n\002id\030\001 \001(\004\022\017\n\007content\030\002 \001(\t" +
      "\"%\n\nGetRequest\022\013\n\003all\030\001 \001(\010\022\n\n\002id\030\002 \001(\004\"" +
      "0\n\021TestAndSetRequest\022\n\n\002id\030\001 \001(\004\022\017\n\007cont" +
      "ent\030\002 \001(\t\"\030\n\nDelRequest\022\n\n\002id\030\001 \001(\0042\323\001\n\013" +
      "CrudService\022,\n\003set\022\020.crud.SetRequest\032\023.c" +
      "rud.ResponseModel\022,\n\003get\022\020.crud.GetReque" +
      "st\032\023.crud.ResponseModel\022:\n\ntestAndSet\022\027." +
      "crud.TestAndSetRequest\032\023.crud.ResponseMo" +
      "del\022,\n\003del\022\020.crud.DelRequest\032\023.crud.Resp" +
      "onseModelB\026\n\022com.projetosd.grpcP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_crud_ResponseModel_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_crud_ResponseModel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crud_ResponseModel_descriptor,
        new java.lang.String[] { "Success", "Response", });
    internal_static_crud_SetRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_crud_SetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crud_SetRequest_descriptor,
        new java.lang.String[] { "Id", "Content", });
    internal_static_crud_GetRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_crud_GetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crud_GetRequest_descriptor,
        new java.lang.String[] { "All", "Id", });
    internal_static_crud_TestAndSetRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_crud_TestAndSetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crud_TestAndSetRequest_descriptor,
        new java.lang.String[] { "Id", "Content", });
    internal_static_crud_DelRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_crud_DelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_crud_DelRequest_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
