// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crudService.proto

package com.projetosd.grpc;

public interface DelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crud.DelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 id = 1;</code>
   */
  long getId();
}
