// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crudService.proto

package com.projetosd.grpc;

/**
 * Protobuf type {@code crud.Dto}
 */
public  final class Dto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:crud.Dto)
    DtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Dto.newBuilder() to construct.
  private Dto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Dto() {
    i_ = 0;
    s_ = "";
    b_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Dto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            i_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            s_ = s;
            break;
          }
          case 24: {

            b_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.projetosd.grpc.CrudProto.internal_static_crud_Dto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.projetosd.grpc.CrudProto.internal_static_crud_Dto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.projetosd.grpc.Dto.class, com.projetosd.grpc.Dto.Builder.class);
  }

  public static final int I_FIELD_NUMBER = 1;
  private int i_;
  /**
   * <code>int32 i = 1;</code>
   */
  public int getI() {
    return i_;
  }

  public static final int S_FIELD_NUMBER = 2;
  private volatile java.lang.Object s_;
  /**
   * <code>string s = 2;</code>
   */
  public java.lang.String getS() {
    java.lang.Object ref = s_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      s_ = s;
      return s;
    }
  }
  /**
   * <code>string s = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSBytes() {
    java.lang.Object ref = s_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      s_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int B_FIELD_NUMBER = 3;
  private boolean b_;
  /**
   * <code>bool b = 3;</code>
   */
  public boolean getB() {
    return b_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (i_ != 0) {
      output.writeInt32(1, i_);
    }
    if (!getSBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, s_);
    }
    if (b_ != false) {
      output.writeBool(3, b_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (i_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, i_);
    }
    if (!getSBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, s_);
    }
    if (b_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, b_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.projetosd.grpc.Dto)) {
      return super.equals(obj);
    }
    com.projetosd.grpc.Dto other = (com.projetosd.grpc.Dto) obj;

    boolean result = true;
    result = result && (getI()
        == other.getI());
    result = result && getS()
        .equals(other.getS());
    result = result && (getB()
        == other.getB());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + I_FIELD_NUMBER;
    hash = (53 * hash) + getI();
    hash = (37 * hash) + S_FIELD_NUMBER;
    hash = (53 * hash) + getS().hashCode();
    hash = (37 * hash) + B_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getB());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.projetosd.grpc.Dto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.projetosd.grpc.Dto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.projetosd.grpc.Dto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.projetosd.grpc.Dto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.projetosd.grpc.Dto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.projetosd.grpc.Dto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.projetosd.grpc.Dto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.projetosd.grpc.Dto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.projetosd.grpc.Dto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.projetosd.grpc.Dto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.projetosd.grpc.Dto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.projetosd.grpc.Dto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.projetosd.grpc.Dto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code crud.Dto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:crud.Dto)
      com.projetosd.grpc.DtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.projetosd.grpc.CrudProto.internal_static_crud_Dto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.projetosd.grpc.CrudProto.internal_static_crud_Dto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.projetosd.grpc.Dto.class, com.projetosd.grpc.Dto.Builder.class);
    }

    // Construct using com.projetosd.grpc.Dto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      i_ = 0;

      s_ = "";

      b_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.projetosd.grpc.CrudProto.internal_static_crud_Dto_descriptor;
    }

    @java.lang.Override
    public com.projetosd.grpc.Dto getDefaultInstanceForType() {
      return com.projetosd.grpc.Dto.getDefaultInstance();
    }

    @java.lang.Override
    public com.projetosd.grpc.Dto build() {
      com.projetosd.grpc.Dto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.projetosd.grpc.Dto buildPartial() {
      com.projetosd.grpc.Dto result = new com.projetosd.grpc.Dto(this);
      result.i_ = i_;
      result.s_ = s_;
      result.b_ = b_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.projetosd.grpc.Dto) {
        return mergeFrom((com.projetosd.grpc.Dto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.projetosd.grpc.Dto other) {
      if (other == com.projetosd.grpc.Dto.getDefaultInstance()) return this;
      if (other.getI() != 0) {
        setI(other.getI());
      }
      if (!other.getS().isEmpty()) {
        s_ = other.s_;
        onChanged();
      }
      if (other.getB() != false) {
        setB(other.getB());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.projetosd.grpc.Dto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.projetosd.grpc.Dto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int i_ ;
    /**
     * <code>int32 i = 1;</code>
     */
    public int getI() {
      return i_;
    }
    /**
     * <code>int32 i = 1;</code>
     */
    public Builder setI(int value) {
      
      i_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 i = 1;</code>
     */
    public Builder clearI() {
      
      i_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object s_ = "";
    /**
     * <code>string s = 2;</code>
     */
    public java.lang.String getS() {
      java.lang.Object ref = s_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        s_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string s = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSBytes() {
      java.lang.Object ref = s_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        s_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string s = 2;</code>
     */
    public Builder setS(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      s_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string s = 2;</code>
     */
    public Builder clearS() {
      
      s_ = getDefaultInstance().getS();
      onChanged();
      return this;
    }
    /**
     * <code>string s = 2;</code>
     */
    public Builder setSBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      s_ = value;
      onChanged();
      return this;
    }

    private boolean b_ ;
    /**
     * <code>bool b = 3;</code>
     */
    public boolean getB() {
      return b_;
    }
    /**
     * <code>bool b = 3;</code>
     */
    public Builder setB(boolean value) {
      
      b_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool b = 3;</code>
     */
    public Builder clearB() {
      
      b_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:crud.Dto)
  }

  // @@protoc_insertion_point(class_scope:crud.Dto)
  private static final com.projetosd.grpc.Dto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.projetosd.grpc.Dto();
  }

  public static com.projetosd.grpc.Dto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Dto>
      PARSER = new com.google.protobuf.AbstractParser<Dto>() {
    @java.lang.Override
    public Dto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Dto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Dto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Dto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.projetosd.grpc.Dto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

