// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crudService.proto

package com.projetosd.grpc;

public interface DtoListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crud.DtoList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .crud.Dto dto = 1;</code>
   */
  java.util.List<com.projetosd.grpc.Dto> 
      getDtoList();
  /**
   * <code>repeated .crud.Dto dto = 1;</code>
   */
  com.projetosd.grpc.Dto getDto(int index);
  /**
   * <code>repeated .crud.Dto dto = 1;</code>
   */
  int getDtoCount();
  /**
   * <code>repeated .crud.Dto dto = 1;</code>
   */
  java.util.List<? extends com.projetosd.grpc.DtoOrBuilder> 
      getDtoOrBuilderList();
  /**
   * <code>repeated .crud.Dto dto = 1;</code>
   */
  com.projetosd.grpc.DtoOrBuilder getDtoOrBuilder(
      int index);
}
