// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crudService.proto

package com.projetosd.grpc;

/**
 * Protobuf type {@code crud.DtoList}
 */
public  final class DtoList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:crud.DtoList)
    DtoListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DtoList.newBuilder() to construct.
  private DtoList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DtoList() {
    dto_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DtoList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              dto_ = new java.util.ArrayList<com.projetosd.grpc.Dto>();
              mutable_bitField0_ |= 0x00000001;
            }
            dto_.add(
                input.readMessage(com.projetosd.grpc.Dto.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        dto_ = java.util.Collections.unmodifiableList(dto_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.projetosd.grpc.CrudProto.internal_static_crud_DtoList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.projetosd.grpc.CrudProto.internal_static_crud_DtoList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.projetosd.grpc.DtoList.class, com.projetosd.grpc.DtoList.Builder.class);
  }

  public static final int DTO_FIELD_NUMBER = 1;
  private java.util.List<com.projetosd.grpc.Dto> dto_;
  /**
   * <code>repeated .crud.Dto dto = 1;</code>
   */
  public java.util.List<com.projetosd.grpc.Dto> getDtoList() {
    return dto_;
  }
  /**
   * <code>repeated .crud.Dto dto = 1;</code>
   */
  public java.util.List<? extends com.projetosd.grpc.DtoOrBuilder> 
      getDtoOrBuilderList() {
    return dto_;
  }
  /**
   * <code>repeated .crud.Dto dto = 1;</code>
   */
  public int getDtoCount() {
    return dto_.size();
  }
  /**
   * <code>repeated .crud.Dto dto = 1;</code>
   */
  public com.projetosd.grpc.Dto getDto(int index) {
    return dto_.get(index);
  }
  /**
   * <code>repeated .crud.Dto dto = 1;</code>
   */
  public com.projetosd.grpc.DtoOrBuilder getDtoOrBuilder(
      int index) {
    return dto_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < dto_.size(); i++) {
      output.writeMessage(1, dto_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < dto_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, dto_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.projetosd.grpc.DtoList)) {
      return super.equals(obj);
    }
    com.projetosd.grpc.DtoList other = (com.projetosd.grpc.DtoList) obj;

    boolean result = true;
    result = result && getDtoList()
        .equals(other.getDtoList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDtoCount() > 0) {
      hash = (37 * hash) + DTO_FIELD_NUMBER;
      hash = (53 * hash) + getDtoList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.projetosd.grpc.DtoList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.projetosd.grpc.DtoList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.projetosd.grpc.DtoList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.projetosd.grpc.DtoList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.projetosd.grpc.DtoList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.projetosd.grpc.DtoList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.projetosd.grpc.DtoList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.projetosd.grpc.DtoList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.projetosd.grpc.DtoList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.projetosd.grpc.DtoList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.projetosd.grpc.DtoList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.projetosd.grpc.DtoList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.projetosd.grpc.DtoList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code crud.DtoList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:crud.DtoList)
      com.projetosd.grpc.DtoListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.projetosd.grpc.CrudProto.internal_static_crud_DtoList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.projetosd.grpc.CrudProto.internal_static_crud_DtoList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.projetosd.grpc.DtoList.class, com.projetosd.grpc.DtoList.Builder.class);
    }

    // Construct using com.projetosd.grpc.DtoList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDtoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (dtoBuilder_ == null) {
        dto_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        dtoBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.projetosd.grpc.CrudProto.internal_static_crud_DtoList_descriptor;
    }

    @java.lang.Override
    public com.projetosd.grpc.DtoList getDefaultInstanceForType() {
      return com.projetosd.grpc.DtoList.getDefaultInstance();
    }

    @java.lang.Override
    public com.projetosd.grpc.DtoList build() {
      com.projetosd.grpc.DtoList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.projetosd.grpc.DtoList buildPartial() {
      com.projetosd.grpc.DtoList result = new com.projetosd.grpc.DtoList(this);
      int from_bitField0_ = bitField0_;
      if (dtoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          dto_ = java.util.Collections.unmodifiableList(dto_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.dto_ = dto_;
      } else {
        result.dto_ = dtoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.projetosd.grpc.DtoList) {
        return mergeFrom((com.projetosd.grpc.DtoList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.projetosd.grpc.DtoList other) {
      if (other == com.projetosd.grpc.DtoList.getDefaultInstance()) return this;
      if (dtoBuilder_ == null) {
        if (!other.dto_.isEmpty()) {
          if (dto_.isEmpty()) {
            dto_ = other.dto_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDtoIsMutable();
            dto_.addAll(other.dto_);
          }
          onChanged();
        }
      } else {
        if (!other.dto_.isEmpty()) {
          if (dtoBuilder_.isEmpty()) {
            dtoBuilder_.dispose();
            dtoBuilder_ = null;
            dto_ = other.dto_;
            bitField0_ = (bitField0_ & ~0x00000001);
            dtoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDtoFieldBuilder() : null;
          } else {
            dtoBuilder_.addAllMessages(other.dto_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.projetosd.grpc.DtoList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.projetosd.grpc.DtoList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.projetosd.grpc.Dto> dto_ =
      java.util.Collections.emptyList();
    private void ensureDtoIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        dto_ = new java.util.ArrayList<com.projetosd.grpc.Dto>(dto_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.projetosd.grpc.Dto, com.projetosd.grpc.Dto.Builder, com.projetosd.grpc.DtoOrBuilder> dtoBuilder_;

    /**
     * <code>repeated .crud.Dto dto = 1;</code>
     */
    public java.util.List<com.projetosd.grpc.Dto> getDtoList() {
      if (dtoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(dto_);
      } else {
        return dtoBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .crud.Dto dto = 1;</code>
     */
    public int getDtoCount() {
      if (dtoBuilder_ == null) {
        return dto_.size();
      } else {
        return dtoBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .crud.Dto dto = 1;</code>
     */
    public com.projetosd.grpc.Dto getDto(int index) {
      if (dtoBuilder_ == null) {
        return dto_.get(index);
      } else {
        return dtoBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .crud.Dto dto = 1;</code>
     */
    public Builder setDto(
        int index, com.projetosd.grpc.Dto value) {
      if (dtoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDtoIsMutable();
        dto_.set(index, value);
        onChanged();
      } else {
        dtoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .crud.Dto dto = 1;</code>
     */
    public Builder setDto(
        int index, com.projetosd.grpc.Dto.Builder builderForValue) {
      if (dtoBuilder_ == null) {
        ensureDtoIsMutable();
        dto_.set(index, builderForValue.build());
        onChanged();
      } else {
        dtoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .crud.Dto dto = 1;</code>
     */
    public Builder addDto(com.projetosd.grpc.Dto value) {
      if (dtoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDtoIsMutable();
        dto_.add(value);
        onChanged();
      } else {
        dtoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .crud.Dto dto = 1;</code>
     */
    public Builder addDto(
        int index, com.projetosd.grpc.Dto value) {
      if (dtoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDtoIsMutable();
        dto_.add(index, value);
        onChanged();
      } else {
        dtoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .crud.Dto dto = 1;</code>
     */
    public Builder addDto(
        com.projetosd.grpc.Dto.Builder builderForValue) {
      if (dtoBuilder_ == null) {
        ensureDtoIsMutable();
        dto_.add(builderForValue.build());
        onChanged();
      } else {
        dtoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .crud.Dto dto = 1;</code>
     */
    public Builder addDto(
        int index, com.projetosd.grpc.Dto.Builder builderForValue) {
      if (dtoBuilder_ == null) {
        ensureDtoIsMutable();
        dto_.add(index, builderForValue.build());
        onChanged();
      } else {
        dtoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .crud.Dto dto = 1;</code>
     */
    public Builder addAllDto(
        java.lang.Iterable<? extends com.projetosd.grpc.Dto> values) {
      if (dtoBuilder_ == null) {
        ensureDtoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dto_);
        onChanged();
      } else {
        dtoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .crud.Dto dto = 1;</code>
     */
    public Builder clearDto() {
      if (dtoBuilder_ == null) {
        dto_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        dtoBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .crud.Dto dto = 1;</code>
     */
    public Builder removeDto(int index) {
      if (dtoBuilder_ == null) {
        ensureDtoIsMutable();
        dto_.remove(index);
        onChanged();
      } else {
        dtoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .crud.Dto dto = 1;</code>
     */
    public com.projetosd.grpc.Dto.Builder getDtoBuilder(
        int index) {
      return getDtoFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .crud.Dto dto = 1;</code>
     */
    public com.projetosd.grpc.DtoOrBuilder getDtoOrBuilder(
        int index) {
      if (dtoBuilder_ == null) {
        return dto_.get(index);  } else {
        return dtoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .crud.Dto dto = 1;</code>
     */
    public java.util.List<? extends com.projetosd.grpc.DtoOrBuilder> 
         getDtoOrBuilderList() {
      if (dtoBuilder_ != null) {
        return dtoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(dto_);
      }
    }
    /**
     * <code>repeated .crud.Dto dto = 1;</code>
     */
    public com.projetosd.grpc.Dto.Builder addDtoBuilder() {
      return getDtoFieldBuilder().addBuilder(
          com.projetosd.grpc.Dto.getDefaultInstance());
    }
    /**
     * <code>repeated .crud.Dto dto = 1;</code>
     */
    public com.projetosd.grpc.Dto.Builder addDtoBuilder(
        int index) {
      return getDtoFieldBuilder().addBuilder(
          index, com.projetosd.grpc.Dto.getDefaultInstance());
    }
    /**
     * <code>repeated .crud.Dto dto = 1;</code>
     */
    public java.util.List<com.projetosd.grpc.Dto.Builder> 
         getDtoBuilderList() {
      return getDtoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.projetosd.grpc.Dto, com.projetosd.grpc.Dto.Builder, com.projetosd.grpc.DtoOrBuilder> 
        getDtoFieldBuilder() {
      if (dtoBuilder_ == null) {
        dtoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.projetosd.grpc.Dto, com.projetosd.grpc.Dto.Builder, com.projetosd.grpc.DtoOrBuilder>(
                dto_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        dto_ = null;
      }
      return dtoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:crud.DtoList)
  }

  // @@protoc_insertion_point(class_scope:crud.DtoList)
  private static final com.projetosd.grpc.DtoList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.projetosd.grpc.DtoList();
  }

  public static com.projetosd.grpc.DtoList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DtoList>
      PARSER = new com.google.protobuf.AbstractParser<DtoList>() {
    @java.lang.Override
    public DtoList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DtoList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DtoList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DtoList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.projetosd.grpc.DtoList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

