// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crudService.proto

package com.projetosd.grpc;

public interface DtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crud.Dto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 i = 1;</code>
   */
  int getI();

  /**
   * <code>string s = 2;</code>
   */
  java.lang.String getS();
  /**
   * <code>string s = 2;</code>
   */
  com.google.protobuf.ByteString
      getSBytes();

  /**
   * <code>bool b = 3;</code>
   */
  boolean getB();
}
