// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crudService.proto

package com.projetosd.grpc;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crud.Empty)
    com.google.protobuf.MessageOrBuilder {
}
