// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crudService.proto

package com.projetosd.grpc;

public interface GetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crud.GetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool all = 1;</code>
   */
  boolean getAll();

  /**
   * <code>uint64 id = 2;</code>
   */
  long getId();
}
