// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crudService.proto

package com.projetosd.grpc;

public interface ResponseModelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:crud.ResponseModel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>string response = 2;</code>
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 2;</code>
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
